insert into time (id_servidor, id_pais, id_usuario, nome, sigla) values (1, 1, -1, 'Clube Atletico Paranaense','CAP');
insert into time (id_servidor, id_pais, id_usuario, nome, sigla) values (1, 1, -1, 'Atletico Goianiense','CAG');
insert into time (id_servidor, id_pais, id_usuario, nome, sigla) values (1, 1, -1, 'Clube Atletico Mineiro','ATM');
insert into time (id_servidor, id_pais, id_usuario, nome, sigla) values (1, 1, -1, 'Esporte Clube Bahia','BAH');
insert into time (id_servidor, id_pais, id_usuario, nome, sigla) values (1, 1, -1, 'Botafogo','BOT');
insert into time (id_servidor, id_pais, id_usuario, nome, sigla) values (1, 1, -1, 'Clube Atletico Bragantino','BRA');
insert into time (id_servidor, id_pais, id_usuario, nome, sigla) values (1, 1, -1, 'Ceará','CEA');
insert into time (id_servidor, id_pais, id_usuario, nome, sigla) values (1, 1, -1, 'Esporte Clube Corinthians Paulista','COR');
insert into time (id_servidor, id_pais, id_usuario, nome, sigla) values (1, 1, -1, 'Coritiba Foot ball Clube','CTB');
insert into time (id_servidor, id_pais, id_usuario, nome, sigla) values (1, 1, -1, 'Clube de Regatas Flamengo','FLA');
insert into time (id_servidor, id_pais, id_usuario, nome, sigla) values (1, 1, -1, 'Fluminense','FLU');
insert into time (id_servidor, id_pais, id_usuario, nome, sigla) values (1, 1, -1, 'Fortaleza','FOR');
insert into time (id_servidor, id_pais, id_usuario, nome, sigla) values (1, 1, -1, 'Goias','GOI');
insert into time (id_servidor, id_pais, id_usuario, nome, sigla) values (1, 1, -1, 'Gremio','GRE');
insert into time (id_servidor, id_pais, id_usuario, nome, sigla) values (1, 1, -1, 'Internacional','INT');
insert into time (id_servidor, id_pais, id_usuario, nome, sigla) values (1, 1, -1, 'Palmeiras','PAL');
insert into time (id_servidor, id_pais, id_usuario, nome, sigla) values (1, 1, -1, 'Santos Futebol Clube','SAN');
insert into time (id_servidor, id_pais, id_usuario, nome, sigla) values (1, 1, -1, 'São Paulo','SAO');
insert into time (id_servidor, id_pais, id_usuario, nome, sigla) values (1, 1, -1, 'Sport Recife','SPO');
insert into time (id_servidor, id_pais, id_usuario, nome, sigla) values (1, 1, -1, 'Vasco da Gama','VAS');