insert into time_base (id_time_base, id_pais, nome, sigla) values (-1, 1, 'CLUBE BASE','CBS');
insert into time_base (id_pais, nome, sigla) values (1, 'Clube Atletico Paranaense','CAP');
insert into time_base (id_pais, nome, sigla) values (1, 'Atletico Goianiense','CAG');
insert into time_base (id_pais, nome, sigla) values (1, 'Clube Atletico Mineiro','ATM');
insert into time_base (id_pais, nome, sigla) values (1, 'Esporte Clube Bahia','BAH');
insert into time_base (id_pais, nome, sigla) values (1, 'Botafogo','BOT');
insert into time_base (id_pais, nome, sigla) values (1, 'Clube Atletico Bragantino','BRA');
insert into time_base (id_pais, nome, sigla) values (1, 'Ceará','CEA');
insert into time_base (id_pais, nome, sigla) values (1, 'Esporte Clube Corinthians Paulista','COR');
insert into time_base (id_pais, nome, sigla) values (1, 'Coritiba Foot ball Clube','CTB');
insert into time_base (id_pais, nome, sigla) values (1, 'Clube de Regatas Flamengo','FLA');
insert into time_base (id_pais, nome, sigla) values (1, 'Fluminense','FLU');
insert into time_base (id_pais, nome, sigla) values (1, 'Fortaleza','FOR');
insert into time_base (id_pais, nome, sigla) values (1, 'Goias','GOI');
insert into time_base (id_pais, nome, sigla) values (1, 'Gremio','GRE');
insert into time_base (id_pais, nome, sigla) values (1, 'Internacional','INT');
insert into time_base (id_pais, nome, sigla) values (1, 'Palmeiras','PAL');
insert into time_base (id_pais, nome, sigla) values (1, 'Santos Futebol Clube','SAN');
insert into time_base (id_pais, nome, sigla) values (1, 'São Paulo','SAO');
insert into time_base (id_pais, nome, sigla) values (1, 'Sport Recife','SPO');
insert into time_base (id_pais, nome, sigla) values (1, 'Vasco da Gama','VAS');