insert into jogador (id_time, id_pais, nome, posicao, nascimento, forca) values (1,1,'Santos','G',1990,45);
insert into jogador (id_time, id_pais, nome, posicao, nascimento, forca) values (1,1,'Jandrei','G',1990,40);
insert into jogador (id_time, id_pais, nome, posicao, nascimento, forca) values (1,1,'Jonathan','L',1990,40);
insert into jogador (id_time, id_pais, nome, posicao, nascimento, forca) values (1,1,'Márcio Azevedo','L',1990,40);
insert into jogador (id_time, id_pais, nome, posicao, nascimento, forca) values (1,1,'Khellven','L',1990,35);
insert into jogador (id_time, id_pais, nome, posicao, nascimento, forca) values (1,1,'Thiago Heleno','Z',1990,40);
insert into jogador (id_time, id_pais, nome, posicao, nascimento, forca) values (1,1,'Lucas Halter','Z',1990,40);
insert into jogador (id_time, id_pais, nome, posicao, nascimento, forca) values (1,1,'Zé Ivaldo','Z',1990,35);
insert into jogador (id_time, id_pais, nome, posicao, nascimento, forca) values (1,1,'Léo Cittadini','M',1990,40);
insert into jogador (id_time, id_pais, nome, posicao, nascimento, forca) values (1,1,'Nikão','M',1990,40);
insert into jogador (id_time, id_pais, nome, posicao, nascimento, forca) values (1,1,'Wellington','M',1990,40);
insert into jogador (id_time, id_pais, nome, posicao, nascimento, forca) values (1,1,'Erick','M',1990,40);
insert into jogador (id_time, id_pais, nome, posicao, nascimento, forca) values (1,1,'Carlos Eduardo','A',1990,40);
insert into jogador (id_time, id_pais, nome, posicao, nascimento, forca) values (1,1,'Marquinhos Gabriel','A',1990,40);
insert into jogador (id_time, id_pais, nome, posicao, nascimento, forca) values (1,1,'Pedrinho','A',1990,35);
insert into jogador (id_time, id_pais, nome, posicao, nascimento, forca) values (2,1,'Mauricio Kozlinski','G',1990,38);
insert into jogador (id_time, id_pais, nome, posicao, nascimento, forca) values (2,1,'Jean','G',1990,35);
insert into jogador (id_time, id_pais, nome, posicao, nascimento, forca) values (2,1,'Dudu','L',1990,38);
insert into jogador (id_time, id_pais, nome, posicao, nascimento, forca) values (2,1,'Moraes','L',1990,38);
insert into jogador (id_time, id_pais, nome, posicao, nascimento, forca) values (2,1,'Nicolas','L',1990,35);
insert into jogador (id_time, id_pais, nome, posicao, nascimento, forca) values (2,1,'Oliveira','Z',1990,38);
insert into jogador (id_time, id_pais, nome, posicao, nascimento, forca) values (2,1,'Gilvan','Z',1990,38);
insert into jogador (id_time, id_pais, nome, posicao, nascimento, forca) values (2,1,'Éder','Z',1990,35);
insert into jogador (id_time, id_pais, nome, posicao, nascimento, forca) values (2,1,'Caio Vinícius','M',1990,40);
insert into jogador (id_time, id_pais, nome, posicao, nascimento, forca) values (2,1,'Matheus Vargas','M',1990,38);
insert into jogador (id_time, id_pais, nome, posicao, nascimento, forca) values (2,1,'Édson','M',1990,35);
insert into jogador (id_time, id_pais, nome, posicao, nascimento, forca) values (2,1,'Marlon Freitas','M',1990,35);
insert into jogador (id_time, id_pais, nome, posicao, nascimento, forca) values (2,1,'Reginaldo','A',1990,40);
insert into jogador (id_time, id_pais, nome, posicao, nascimento, forca) values (2,1,'Cristhyan','A',1990,38);
insert into jogador (id_time, id_pais, nome, posicao, nascimento, forca) values (2,1,'Júlio César','A',1990,35);
insert into jogador (id_time, id_pais, nome, posicao, nascimento, forca) values (3,1,'Rafael','G',1990,40);
insert into jogador (id_time, id_pais, nome, posicao, nascimento, forca) values (3,1,'Michael','G',1990,40);
insert into jogador (id_time, id_pais, nome, posicao, nascimento, forca) values (3,1,'Fábio Santos','L',1990,38);
insert into jogador (id_time, id_pais, nome, posicao, nascimento, forca) values (3,1,'Guilherme Arana','L',1990,40);
insert into jogador (id_time, id_pais, nome, posicao, nascimento, forca) values (3,1,'Guga','L',1990,40);
insert into jogador (id_time, id_pais, nome, posicao, nascimento, forca) values (3,1,'Réver','Z',1990,38);
insert into jogador (id_time, id_pais, nome, posicao, nascimento, forca) values (3,1,'Gabriel','Z',1990,38);
insert into jogador (id_time, id_pais, nome, posicao, nascimento, forca) values (3,1,'Igor Rabello','Z',1990,38);
insert into jogador (id_time, id_pais, nome, posicao, nascimento, forca) values (3,12,'Otero','M',1990,42);
insert into jogador (id_time, id_pais, nome, posicao, nascimento, forca) values (3,1,'Hyoran','M',1990,38);
insert into jogador (id_time, id_pais, nome, posicao, nascimento, forca) values (3,12,'Savarino','M',1990,38);
insert into jogador (id_time, id_pais, nome, posicao, nascimento, forca) values (3,1,'Allan','M',1990,40);
insert into jogador (id_time, id_pais, nome, posicao, nascimento, forca) values (3,1,'Ricardo Oliveira','A',1990,40);
insert into jogador (id_time, id_pais, nome, posicao, nascimento, forca) values (3,1,'Di Santo','A',1990,40);
insert into jogador (id_time, id_pais, nome, posicao, nascimento, forca) values (3,1,'Nathan','A',1990,40);
insert into jogador (id_time, id_pais, nome, posicao, nascimento, forca) values (4,1,'Douglas','G',1990,40);
insert into jogador (id_time, id_pais, nome, posicao, nascimento, forca) values (4,1,'Anderson','G',1990,38);
insert into jogador (id_time, id_pais, nome, posicao, nascimento, forca) values (4,1,'João Pedro','L',1990,40);
insert into jogador (id_time, id_pais, nome, posicao, nascimento, forca) values (4,1,'Zeca','L',1990,38);
insert into jogador (id_time, id_pais, nome, posicao, nascimento, forca) values (4,1,'Nino Paraíba','L',1990,40);
insert into jogador (id_time, id_pais, nome, posicao, nascimento, forca) values (4,1,'Lucas Fonseca','Z',1990,40);
insert into jogador (id_time, id_pais, nome, posicao, nascimento, forca) values (4,1,'Juninho','Z',1990,40);
insert into jogador (id_time, id_pais, nome, posicao, nascimento, forca) values (4,1,'Wanderson','Z',1990,38);
insert into jogador (id_time, id_pais, nome, posicao, nascimento, forca) values (4,1,'Flávio','M',1990,40);
insert into jogador (id_time, id_pais, nome, posicao, nascimento, forca) values (4,1,'Gregore','M',1990,40);
insert into jogador (id_time, id_pais, nome, posicao, nascimento, forca) values (4,1,'Rodriguinho','M',1990,38);
insert into jogador (id_time, id_pais, nome, posicao, nascimento, forca) values (4,1,'Jádson','M',1990,38);
insert into jogador (id_time, id_pais, nome, posicao, nascimento, forca) values (4,1,'Élber','A',1990,38);
insert into jogador (id_time, id_pais, nome, posicao, nascimento, forca) values (4,1,'Gilberto','A',1990,40);
insert into jogador (id_time, id_pais, nome, posicao, nascimento, forca) values (4,1,'Clayson','A',1990,38);
insert into jogador (id_time, id_pais, nome, posicao, nascimento, forca) values (5,16,'Gatito Fernández','G',1990,40);
insert into jogador (id_time, id_pais, nome, posicao, nascimento, forca) values (5,1,'Diego Cavalieri','G',1990,38);
insert into jogador (id_time, id_pais, nome, posicao, nascimento, forca) values (5,1,'Fernando Costanza','L',1990,40);
insert into jogador (id_time, id_pais, nome, posicao, nascimento, forca) values (5,1,'Guilherme Santos','L',1990,40);
insert into jogador (id_time, id_pais, nome, posicao, nascimento, forca) values (5,1,'Lucas Barros','L',1990,35);
insert into jogador (id_time, id_pais, nome, posicao, nascimento, forca) values (5,1,'Kanu','Z',1990,40);
insert into jogador (id_time, id_pais, nome, posicao, nascimento, forca) values (5,1,'Marcelo Benevenuto','Z',1990,38);
insert into jogador (id_time, id_pais, nome, posicao, nascimento, forca) values (5,1,'Ruan Renato','Z',1990,38);
insert into jogador (id_time, id_pais, nome, posicao, nascimento, forca) values (5,1,'Bruno Nazário','M',1990,45);
insert into jogador (id_time, id_pais, nome, posicao, nascimento, forca) values (5,1,'Alex Santana','M',1990,40);
insert into jogador (id_time, id_pais, nome, posicao, nascimento, forca) values (5,1,'Caio Alexandre','M',1990,40);
insert into jogador (id_time, id_pais, nome, posicao, nascimento, forca) values (5,2,'Honda','M',1990,45);
insert into jogador (id_time, id_pais, nome, posicao, nascimento, forca) values (5,1,'Rafael Navarro','A',1990,40);
insert into jogador (id_time, id_pais, nome, posicao, nascimento, forca) values (5,1,'Luiz Fernando','A',1990,38);
insert into jogador (id_time, id_pais, nome, posicao, nascimento, forca) values (5,1,'Luis Henrique','A',1990,35);
insert into jogador (id_time, id_pais, nome, posicao, nascimento, forca) values (6,1,'Júlio César','G',1990,38);
insert into jogador (id_time, id_pais, nome, posicao, nascimento, forca) values (6,1,'Cleiton','G',1990,40);
insert into jogador (id_time, id_pais, nome, posicao, nascimento, forca) values (6,1,'Edimar','L',1990,38);
insert into jogador (id_time, id_pais, nome, posicao, nascimento, forca) values (6,1,'Weverton','L',1990,38);
insert into jogador (id_time, id_pais, nome, posicao, nascimento, forca) values (6,1,'Luan Cândido','L',1990,38);
insert into jogador (id_time, id_pais, nome, posicao, nascimento, forca) values (6,1,'Ligger','Z',1990,40);
insert into jogador (id_time, id_pais, nome, posicao, nascimento, forca) values (6,1,'Léo Ortiz','Z',1990,40);
insert into jogador (id_time, id_pais, nome, posicao, nascimento, forca) values (6,1,'Fabrício Bruno','Z',1990,38);
insert into jogador (id_time, id_pais, nome, posicao, nascimento, forca) values (6,1,'Uillian Correia','M',1990,40);
insert into jogador (id_time, id_pais, nome, posicao, nascimento, forca) values (6,1,'Barreto','M',1990,40);
insert into jogador (id_time, id_pais, nome, posicao, nascimento, forca) values (6,1,'Claudinho','M',1990,38);
insert into jogador (id_time, id_pais, nome, posicao, nascimento, forca) values (6,1,'Thonny Anderson','M',1990,43);
insert into jogador (id_time, id_pais, nome, posicao, nascimento, forca) values (6,1,'Artur','A',1990,45);
insert into jogador (id_time, id_pais, nome, posicao, nascimento, forca) values (6,1,'Ytalo','A',1990,40);
insert into jogador (id_time, id_pais, nome, posicao, nascimento, forca) values (6,1,'Morato','A',1990,38);
insert into jogador (id_time, id_pais, nome, posicao, nascimento, forca) values (7,1,'Diogo Silva','G',1990,40);
insert into jogador (id_time, id_pais, nome, posicao, nascimento, forca) values (7,1,'Fernando Prass','G',1990,40);
insert into jogador (id_time, id_pais, nome, posicao, nascimento, forca) values (7,1,'Eduardo','L',1990,38);
insert into jogador (id_time, id_pais, nome, posicao, nascimento, forca) values (7,1,'Kelvyn','L',1990,38);
insert into jogador (id_time, id_pais, nome, posicao, nascimento, forca) values (7,1,'Samuel Xavier','L',1990,38);
insert into jogador (id_time, id_pais, nome, posicao, nascimento, forca) values (7,1,'Eduardo Brock','Z',1990,38);
insert into jogador (id_time, id_pais, nome, posicao, nascimento, forca) values (7,1,'Klaus','Z',1990,38);
insert into jogador (id_time, id_pais, nome, posicao, nascimento, forca) values (7,1,'Luiz Otávio','Z',1990,35);
insert into jogador (id_time, id_pais, nome, posicao, nascimento, forca) values (7,1,'Fabinho','M',1990,38);
insert into jogador (id_time, id_pais, nome, posicao, nascimento, forca) values (7,1,'Fernando Sobral','M',1990,38);
insert into jogador (id_time, id_pais, nome, posicao, nascimento, forca) values (7,1,'Ricardinho','M',1990,36);
insert into jogador (id_time, id_pais, nome, posicao, nascimento, forca) values (7,1,'Lima','M',1990,38);
insert into jogador (id_time, id_pais, nome, posicao, nascimento, forca) values (7,1,'Mateus Gonçalves','A',1990,38);
insert into jogador (id_time, id_pais, nome, posicao, nascimento, forca) values (7,1,'Rodrigão','A',1990,36);
insert into jogador (id_time, id_pais, nome, posicao, nascimento, forca) values (7,1,'Bérgson','A',1990,36);
insert into jogador (id_time, id_pais, nome, posicao, nascimento, forca) values (8,1,'Cássio','G',1990,45);
insert into jogador (id_time, id_pais, nome, posicao, nascimento, forca) values (8,1,'Walter','G',1990,42);
insert into jogador (id_time, id_pais, nome, posicao, nascimento, forca) values (8,1,'Sidcley','L',1990,42);
insert into jogador (id_time, id_pais, nome, posicao, nascimento, forca) values (8,1,'Fagner','L',1990,45);
insert into jogador (id_time, id_pais, nome, posicao, nascimento, forca) values (8,1,'Lucas Piton','L',1990,40);
insert into jogador (id_time, id_pais, nome, posicao, nascimento, forca) values (8,1,'Gil','Z',1990,42);
insert into jogador (id_time, id_pais, nome, posicao, nascimento, forca) values (8,1,'Pedro Henrique','Z',1990,43);
insert into jogador (id_time, id_pais, nome, posicao, nascimento, forca) values (8,1,'Marllon','Z',1990,42);
insert into jogador (id_time, id_pais, nome, posicao, nascimento, forca) values (8,9,'Víctor Cantillo','M',1990,45);
insert into jogador (id_time, id_pais, nome, posicao, nascimento, forca) values (8,1,'Pedrinho','M',1990,45);
insert into jogador (id_time, id_pais, nome, posicao, nascimento, forca) values (8,1,'Luan ','M',1990,45);
insert into jogador (id_time, id_pais, nome, posicao, nascimento, forca) values (8,1,'Camacho','M',1990,40);
insert into jogador (id_time, id_pais, nome, posicao, nascimento, forca) values (8,1,'Vágner Love','A',1990,42);
insert into jogador (id_time, id_pais, nome, posicao, nascimento, forca) values (8,10,'Mauro Boselli','A',1990,42);
insert into jogador (id_time, id_pais, nome, posicao, nascimento, forca) values (8,1,'Everaldo','A',1990,40);
insert into jogador (id_time, id_pais, nome, posicao, nascimento, forca) values (9,1,'Wilson','G',1990,45);
insert into jogador (id_time, id_pais, nome, posicao, nascimento, forca) values (9,1,'Alex Muralha','G',1990,42);
insert into jogador (id_time, id_pais, nome, posicao, nascimento, forca) values (9,1,'Patrick Vieira','L',1990,42);
insert into jogador (id_time, id_pais, nome, posicao, nascimento, forca) values (9,1,'William Matheus','L',1990,45);
insert into jogador (id_time, id_pais, nome, posicao, nascimento, forca) values (9,1,'Lucas Ramon','L',1990,40);
insert into jogador (id_time, id_pais, nome, posicao, nascimento, forca) values (9,1,'Sabino','Z',1990,42);
insert into jogador (id_time, id_pais, nome, posicao, nascimento, forca) values (9,1,'Rhodolfo','Z',1990,43);
insert into jogador (id_time, id_pais, nome, posicao, nascimento, forca) values (9,1,'Rodolfo','Z',1990,42);
insert into jogador (id_time, id_pais, nome, posicao, nascimento, forca) values (9,1,'Matheus Sales','M',1990,45);
insert into jogador (id_time, id_pais, nome, posicao, nascimento, forca) values (9,1,'Renê Júnior','M',1990,45);
insert into jogador (id_time, id_pais, nome, posicao, nascimento, forca) values (9,1,'Ruy','M',1990,45);
insert into jogador (id_time, id_pais, nome, posicao, nascimento, forca) values (9,1,'Thiago Lopes','M',1990,40);
insert into jogador (id_time, id_pais, nome, posicao, nascimento, forca) values (9,1,'Rafinha','A',1990,42);
insert into jogador (id_time, id_pais, nome, posicao, nascimento, forca) values (9,1,'Sassá','A',1990,42);
insert into jogador (id_time, id_pais, nome, posicao, nascimento, forca) values (9,1,'Robson','A',1990,40);
insert into jogador (id_time, id_pais, nome, posicao, nascimento, forca) values (10,1,'Diego Alves','G',1990,45);
insert into jogador (id_time, id_pais, nome, posicao, nascimento, forca) values (10,1,'César','G',1990,42);
insert into jogador (id_time, id_pais, nome, posicao, nascimento, forca) values (10,1,'Rafinha','L',1990,42);
insert into jogador (id_time, id_pais, nome, posicao, nascimento, forca) values (10,1,'Filipe Luís','L',1990,45);
insert into jogador (id_time, id_pais, nome, posicao, nascimento, forca) values (10,1,'Renê','L',1990,40);
insert into jogador (id_time, id_pais, nome, posicao, nascimento, forca) values (10,1,'Rodrigo Caio','Z',1990,42);
insert into jogador (id_time, id_pais, nome, posicao, nascimento, forca) values (10,1,'Gustavo Henrique','Z',1990,43);
insert into jogador (id_time, id_pais, nome, posicao, nascimento, forca) values (10,1,'Léo Pereira','Z',1990,42);
insert into jogador (id_time, id_pais, nome, posicao, nascimento, forca) values (10,1,'Willian Arão','M',1990,45);
insert into jogador (id_time, id_pais, nome, posicao, nascimento, forca) values (10,1,'Diego','M',1990,45);
insert into jogador (id_time, id_pais, nome, posicao, nascimento, forca) values (10,1,'Éverton Ribeiro','M',1990,45);
insert into jogador (id_time, id_pais, nome, posicao, nascimento, forca) values (10,17,'Arrascaeta','M',1990,40);
insert into jogador (id_time, id_pais, nome, posicao, nascimento, forca) values (10,1,'Gerson','M',1990,42);
insert into jogador (id_time, id_pais, nome, posicao, nascimento, forca) values (10,1,'Bruno Henrique','A',1990,42);
insert into jogador (id_time, id_pais, nome, posicao, nascimento, forca) values (10,1,'Gabriel Barbosa','A',1990,40);
insert into jogador (id_time, id_pais, nome, posicao, nascimento, forca) values (10,1,'Pedro','A',1990,40);
insert into jogador (id_time, id_pais, nome, posicao, nascimento, forca) values (10,1,'Michael','A',1990,40);