insert into jogador (id_time, id_pais, nome, posicao, nascimento, forca) values (1,1,'Santos','GL',1990,45);
insert into jogador (id_time, id_pais, nome, posicao, nascimento, forca) values (1,1,'Jandrei','GL',1990,40);
insert into jogador (id_time, id_pais, nome, posicao, nascimento, forca) values (1,1,'Jonathan','LD',1990,40);
insert into jogador (id_time, id_pais, nome, posicao, nascimento, forca) values (1,1,'Márcio Azevedo','LD',1990,40);
insert into jogador (id_time, id_pais, nome, posicao, nascimento, forca) values (1,1,'Khellven','LD',1990,35);
insert into jogador (id_time, id_pais, nome, posicao, nascimento, forca) values (1,1,'Thiago Heleno','ZG',1990,40);
insert into jogador (id_time, id_pais, nome, posicao, nascimento, forca) values (1,1,'Lucas Halter','ZG',1990,40);
insert into jogador (id_time, id_pais, nome, posicao, nascimento, forca) values (1,1,'Zé Ivaldo','ZG',1990,35);
insert into jogador (id_time, id_pais, nome, posicao, nascimento, forca) values (1,1,'Léo Cittadini','MC',1990,40);
insert into jogador (id_time, id_pais, nome, posicao, nascimento, forca) values (1,1,'Nikão','MC',1990,40);
insert into jogador (id_time, id_pais, nome, posicao, nascimento, forca) values (1,1,'Wellington','MC',1990,40);
insert into jogador (id_time, id_pais, nome, posicao, nascimento, forca) values (1,1,'Erick','MC',1990,40);
insert into jogador (id_time, id_pais, nome, posicao, nascimento, forca) values (1,1,'Carlos Eduardo','AT',1990,40);
insert into jogador (id_time, id_pais, nome, posicao, nascimento, forca) values (1,1,'Marquinhos Gabriel','AT',1990,40);
insert into jogador (id_time, id_pais, nome, posicao, nascimento, forca) values (1,1,'Pedrinho','AT',1990,35);
insert into jogador (id_time, id_pais, nome, posicao, nascimento, forca) values (2,1,'Mauricio Kozlinski','GL',1990,38);
insert into jogador (id_time, id_pais, nome, posicao, nascimento, forca) values (2,1,'Jean','GL',1990,35);
insert into jogador (id_time, id_pais, nome, posicao, nascimento, forca) values (2,1,'Dudu','LD',1990,38);
insert into jogador (id_time, id_pais, nome, posicao, nascimento, forca) values (2,1,'Moraes','LD',1990,38);
insert into jogador (id_time, id_pais, nome, posicao, nascimento, forca) values (2,1,'Nicolas','LD',1990,35);
insert into jogador (id_time, id_pais, nome, posicao, nascimento, forca) values (2,1,'Oliveira','ZG',1990,38);
insert into jogador (id_time, id_pais, nome, posicao, nascimento, forca) values (2,1,'Gilvan','ZG',1990,38);
insert into jogador (id_time, id_pais, nome, posicao, nascimento, forca) values (2,1,'Éder','ZG',1990,35);
insert into jogador (id_time, id_pais, nome, posicao, nascimento, forca) values (2,1,'Caio Vinícius','MC',1990,40);
insert into jogador (id_time, id_pais, nome, posicao, nascimento, forca) values (2,1,'Matheus Vargas','MC',1990,38);
insert into jogador (id_time, id_pais, nome, posicao, nascimento, forca) values (2,1,'Édson','MC',1990,35);
insert into jogador (id_time, id_pais, nome, posicao, nascimento, forca) values (2,1,'Marlon Freitas','MC',1990,35);
insert into jogador (id_time, id_pais, nome, posicao, nascimento, forca) values (2,1,'Reginaldo','AT',1990,40);
insert into jogador (id_time, id_pais, nome, posicao, nascimento, forca) values (2,1,'Cristhyan','AT',1990,38);
insert into jogador (id_time, id_pais, nome, posicao, nascimento, forca) values (2,1,'Júlio César','AT',1990,35);
insert into jogador (id_time, id_pais, nome, posicao, nascimento, forca) values (3,1,'Rafael','GL',1990,40);
insert into jogador (id_time, id_pais, nome, posicao, nascimento, forca) values (3,1,'Michael','GL',1990,40);
insert into jogador (id_time, id_pais, nome, posicao, nascimento, forca) values (3,1,'Fábio Santos','LD',1990,38);
insert into jogador (id_time, id_pais, nome, posicao, nascimento, forca) values (3,1,'Guilherme Arana','LD',1990,40);
insert into jogador (id_time, id_pais, nome, posicao, nascimento, forca) values (3,1,'Guga','LD',1990,40);
insert into jogador (id_time, id_pais, nome, posicao, nascimento, forca) values (3,1,'Réver','ZG',1990,38);
insert into jogador (id_time, id_pais, nome, posicao, nascimento, forca) values (3,1,'Gabriel','ZG',1990,38);
insert into jogador (id_time, id_pais, nome, posicao, nascimento, forca) values (3,1,'Igor Rabello','ZG',1990,38);
insert into jogador (id_time, id_pais, nome, posicao, nascimento, forca) values (3,12,'Otero','MC',1990,42);
insert into jogador (id_time, id_pais, nome, posicao, nascimento, forca) values (3,1,'Hyoran','MC',1990,38);
insert into jogador (id_time, id_pais, nome, posicao, nascimento, forca) values (3,12,'Savarino','MC',1990,38);
insert into jogador (id_time, id_pais, nome, posicao, nascimento, forca) values (3,1,'Allan','MC',1990,40);
insert into jogador (id_time, id_pais, nome, posicao, nascimento, forca) values (3,1,'Ricardo Oliveira','AT',1990,40);
insert into jogador (id_time, id_pais, nome, posicao, nascimento, forca) values (3,1,'Di Santo','AT',1990,40);
insert into jogador (id_time, id_pais, nome, posicao, nascimento, forca) values (3,1,'Nathan','AT',1990,40);
insert into jogador (id_time, id_pais, nome, posicao, nascimento, forca) values (4,1,'Douglas','GL',1990,40);
insert into jogador (id_time, id_pais, nome, posicao, nascimento, forca) values (4,1,'Anderson','GL',1990,38);
insert into jogador (id_time, id_pais, nome, posicao, nascimento, forca) values (4,1,'João Pedro','LD',1990,40);
insert into jogador (id_time, id_pais, nome, posicao, nascimento, forca) values (4,1,'Zeca','LD',1990,38);
insert into jogador (id_time, id_pais, nome, posicao, nascimento, forca) values (4,1,'Nino Paraíba','LD',1990,40);
insert into jogador (id_time, id_pais, nome, posicao, nascimento, forca) values (4,1,'Lucas Fonseca','ZG',1990,40);
insert into jogador (id_time, id_pais, nome, posicao, nascimento, forca) values (4,1,'Juninho','ZG',1990,40);
insert into jogador (id_time, id_pais, nome, posicao, nascimento, forca) values (4,1,'Wanderson','ZG',1990,38);
insert into jogador (id_time, id_pais, nome, posicao, nascimento, forca) values (4,1,'Flávio','MC',1990,40);
insert into jogador (id_time, id_pais, nome, posicao, nascimento, forca) values (4,1,'Gregore','MC',1990,40);
insert into jogador (id_time, id_pais, nome, posicao, nascimento, forca) values (4,1,'Rodriguinho','MC',1990,38);
insert into jogador (id_time, id_pais, nome, posicao, nascimento, forca) values (4,1,'Jádson','MC',1990,38);
insert into jogador (id_time, id_pais, nome, posicao, nascimento, forca) values (4,1,'Élber','AT',1990,38);
insert into jogador (id_time, id_pais, nome, posicao, nascimento, forca) values (4,1,'Gilberto','AT',1990,40);
insert into jogador (id_time, id_pais, nome, posicao, nascimento, forca) values (4,1,'Clayson','AT',1990,38);
insert into jogador (id_time, id_pais, nome, posicao, nascimento, forca) values (5,16,'Gatito Fernández','GL',1990,40);
insert into jogador (id_time, id_pais, nome, posicao, nascimento, forca) values (5,1,'Diego Cavalieri','GL',1990,38);
insert into jogador (id_time, id_pais, nome, posicao, nascimento, forca) values (5,1,'Fernando Costanza','LD',1990,40);
insert into jogador (id_time, id_pais, nome, posicao, nascimento, forca) values (5,1,'Guilherme Santos','LD',1990,40);
insert into jogador (id_time, id_pais, nome, posicao, nascimento, forca) values (5,1,'Lucas Barros','LD',1990,35);
insert into jogador (id_time, id_pais, nome, posicao, nascimento, forca) values (5,1,'Kanu','ZG',1990,40);
insert into jogador (id_time, id_pais, nome, posicao, nascimento, forca) values (5,1,'Marcelo Benevenuto','ZG',1990,38);
insert into jogador (id_time, id_pais, nome, posicao, nascimento, forca) values (5,1,'Ruan Renato','ZG',1990,38);
insert into jogador (id_time, id_pais, nome, posicao, nascimento, forca) values (5,1,'Bruno Nazário','MC',1990,45);
insert into jogador (id_time, id_pais, nome, posicao, nascimento, forca) values (5,1,'Alex Santana','MC',1990,40);
insert into jogador (id_time, id_pais, nome, posicao, nascimento, forca) values (5,1,'Caio Alexandre','MC',1990,40);
insert into jogador (id_time, id_pais, nome, posicao, nascimento, forca) values (5,2,'Honda','MC',1990,45);
insert into jogador (id_time, id_pais, nome, posicao, nascimento, forca) values (5,1,'Rafael Navarro','AT',1990,40);
insert into jogador (id_time, id_pais, nome, posicao, nascimento, forca) values (5,1,'Luiz Fernando','AT',1990,38);
insert into jogador (id_time, id_pais, nome, posicao, nascimento, forca) values (5,1,'Luis Henrique','AT',1990,35);
insert into jogador (id_time, id_pais, nome, posicao, nascimento, forca) values (6,1,'Júlio César','GL',1990,38);
insert into jogador (id_time, id_pais, nome, posicao, nascimento, forca) values (6,1,'Cleiton','GL',1990,40);
insert into jogador (id_time, id_pais, nome, posicao, nascimento, forca) values (6,1,'Edimar','LD',1990,38);
insert into jogador (id_time, id_pais, nome, posicao, nascimento, forca) values (6,1,'Weverton','LD',1990,38);
insert into jogador (id_time, id_pais, nome, posicao, nascimento, forca) values (6,1,'Luan Cândido','LD',1990,38);
insert into jogador (id_time, id_pais, nome, posicao, nascimento, forca) values (6,1,'Ligger','ZG',1990,40);
insert into jogador (id_time, id_pais, nome, posicao, nascimento, forca) values (6,1,'Léo Ortiz','ZG',1990,40);
insert into jogador (id_time, id_pais, nome, posicao, nascimento, forca) values (6,1,'Fabrício Bruno','ZG',1990,38);
insert into jogador (id_time, id_pais, nome, posicao, nascimento, forca) values (6,1,'Uillian Correia','MC',1990,40);
insert into jogador (id_time, id_pais, nome, posicao, nascimento, forca) values (6,1,'Barreto','MC',1990,40);
insert into jogador (id_time, id_pais, nome, posicao, nascimento, forca) values (6,1,'Claudinho','MC',1990,38);
insert into jogador (id_time, id_pais, nome, posicao, nascimento, forca) values (6,1,'Thonny Anderson','MC',1990,43);
insert into jogador (id_time, id_pais, nome, posicao, nascimento, forca) values (6,1,'Artur','AT',1990,45);
insert into jogador (id_time, id_pais, nome, posicao, nascimento, forca) values (6,1,'Ytalo','AT',1990,40);
insert into jogador (id_time, id_pais, nome, posicao, nascimento, forca) values (6,1,'Morato','AT',1990,38);
insert into jogador (id_time, id_pais, nome, posicao, nascimento, forca) values (7,1,'Diogo Silva','GL',1990,40);
insert into jogador (id_time, id_pais, nome, posicao, nascimento, forca) values (7,1,'Fernando Prass','GL',1990,40);
insert into jogador (id_time, id_pais, nome, posicao, nascimento, forca) values (7,1,'Eduardo','LD',1990,38);
insert into jogador (id_time, id_pais, nome, posicao, nascimento, forca) values (7,1,'Kelvyn','LD',1990,38);
insert into jogador (id_time, id_pais, nome, posicao, nascimento, forca) values (7,1,'Samuel Xavier','LD',1990,38);
insert into jogador (id_time, id_pais, nome, posicao, nascimento, forca) values (7,1,'Eduardo Brock','ZG',1990,38);
insert into jogador (id_time, id_pais, nome, posicao, nascimento, forca) values (7,1,'Klaus','ZG',1990,38);
insert into jogador (id_time, id_pais, nome, posicao, nascimento, forca) values (7,1,'Luiz Otávio','ZG',1990,35);
insert into jogador (id_time, id_pais, nome, posicao, nascimento, forca) values (7,1,'Fabinho','MC',1990,38);
insert into jogador (id_time, id_pais, nome, posicao, nascimento, forca) values (7,1,'Fernando Sobral','MC',1990,38);
insert into jogador (id_time, id_pais, nome, posicao, nascimento, forca) values (7,1,'Ricardinho','MC',1990,36);
insert into jogador (id_time, id_pais, nome, posicao, nascimento, forca) values (7,1,'Lima','MC',1990,38);
insert into jogador (id_time, id_pais, nome, posicao, nascimento, forca) values (7,1,'Mateus Gonçalves','AT',1990,38);
insert into jogador (id_time, id_pais, nome, posicao, nascimento, forca) values (7,1,'Rodrigão','AT',1990,36);
insert into jogador (id_time, id_pais, nome, posicao, nascimento, forca) values (7,1,'Bérgson','AT',1990,36);
insert into jogador (id_time, id_pais, nome, posicao, nascimento, forca) values (8,1,'Cássio','GL',1990,45);
insert into jogador (id_time, id_pais, nome, posicao, nascimento, forca) values (8,1,'Walter','GL',1990,42);
insert into jogador (id_time, id_pais, nome, posicao, nascimento, forca) values (8,1,'Sidcley','LD',1990,42);
insert into jogador (id_time, id_pais, nome, posicao, nascimento, forca) values (8,1,'Fagner','LD',1990,45);
insert into jogador (id_time, id_pais, nome, posicao, nascimento, forca) values (8,1,'Lucas Piton','LD',1990,40);
insert into jogador (id_time, id_pais, nome, posicao, nascimento, forca) values (8,1,'Gil','ZG',1990,42);
insert into jogador (id_time, id_pais, nome, posicao, nascimento, forca) values (8,1,'Pedro Henrique','ZG',1990,43);
insert into jogador (id_time, id_pais, nome, posicao, nascimento, forca) values (8,1,'Marllon','ZG',1990,42);
insert into jogador (id_time, id_pais, nome, posicao, nascimento, forca) values (8,9,'Víctor Cantillo','MC',1990,45);
insert into jogador (id_time, id_pais, nome, posicao, nascimento, forca) values (8,1,'Pedrinho','MC',1990,45);
insert into jogador (id_time, id_pais, nome, posicao, nascimento, forca) values (8,1,'Luan ','MC',1990,45);
insert into jogador (id_time, id_pais, nome, posicao, nascimento, forca) values (8,1,'Camacho','MC',1990,40);
insert into jogador (id_time, id_pais, nome, posicao, nascimento, forca) values (8,1,'Vágner Love','AT',1990,42);
insert into jogador (id_time, id_pais, nome, posicao, nascimento, forca) values (8,10,'Mauro Boselli','AT',1990,42);
insert into jogador (id_time, id_pais, nome, posicao, nascimento, forca) values (8,1,'Everaldo','AT',1990,40);
insert into jogador (id_time, id_pais, nome, posicao, nascimento, forca) values (9,1,'Wilson','GL',1990,45);
insert into jogador (id_time, id_pais, nome, posicao, nascimento, forca) values (9,1,'Alex Muralha','GL',1990,42);
insert into jogador (id_time, id_pais, nome, posicao, nascimento, forca) values (9,1,'Patrick Vieira','LD',1990,42);
insert into jogador (id_time, id_pais, nome, posicao, nascimento, forca) values (9,1,'William Matheus','LD',1990,45);
insert into jogador (id_time, id_pais, nome, posicao, nascimento, forca) values (9,1,'Lucas Ramon','LD',1990,40);
insert into jogador (id_time, id_pais, nome, posicao, nascimento, forca) values (9,1,'Sabino','ZG',1990,42);
insert into jogador (id_time, id_pais, nome, posicao, nascimento, forca) values (9,1,'Rhodolfo','ZG',1990,43);
insert into jogador (id_time, id_pais, nome, posicao, nascimento, forca) values (9,1,'Rodolfo','ZG',1990,42);
insert into jogador (id_time, id_pais, nome, posicao, nascimento, forca) values (9,1,'Matheus Sales','MC',1990,45);
insert into jogador (id_time, id_pais, nome, posicao, nascimento, forca) values (9,1,'Renê Júnior','MC',1990,45);
insert into jogador (id_time, id_pais, nome, posicao, nascimento, forca) values (9,1,'Ruy','MC',1990,45);
insert into jogador (id_time, id_pais, nome, posicao, nascimento, forca) values (9,1,'Thiago Lopes','MC',1990,40);
insert into jogador (id_time, id_pais, nome, posicao, nascimento, forca) values (9,1,'Rafinha','AT',1990,42);
insert into jogador (id_time, id_pais, nome, posicao, nascimento, forca) values (9,1,'Sassá','AT',1990,42);
insert into jogador (id_time, id_pais, nome, posicao, nascimento, forca) values (9,1,'Robson','AT',1990,40);
insert into jogador (id_time, id_pais, nome, posicao, nascimento, forca) values (10,1,'Diego Alves','GL',1990,45);
insert into jogador (id_time, id_pais, nome, posicao, nascimento, forca) values (10,1,'César','GL',1990,42);
insert into jogador (id_time, id_pais, nome, posicao, nascimento, forca) values (10,1,'Rafinha','LD',1990,42);
insert into jogador (id_time, id_pais, nome, posicao, nascimento, forca) values (10,1,'Filipe Luís','LD',1990,45);
insert into jogador (id_time, id_pais, nome, posicao, nascimento, forca) values (10,1,'Renê','LD',1990,40);
insert into jogador (id_time, id_pais, nome, posicao, nascimento, forca) values (10,1,'Rodrigo Caio','ZG',1990,42);
insert into jogador (id_time, id_pais, nome, posicao, nascimento, forca) values (10,1,'Gustavo Henrique','ZG',1990,43);
insert into jogador (id_time, id_pais, nome, posicao, nascimento, forca) values (10,1,'Léo Pereira','ZG',1990,42);
insert into jogador (id_time, id_pais, nome, posicao, nascimento, forca) values (10,1,'Willian Arão','MC',1990,45);
insert into jogador (id_time, id_pais, nome, posicao, nascimento, forca) values (10,1,'Diego','MC',1990,45);
insert into jogador (id_time, id_pais, nome, posicao, nascimento, forca) values (10,1,'Éverton Ribeiro','MC',1990,45);
insert into jogador (id_time, id_pais, nome, posicao, nascimento, forca) values (10,17,'Arrascaeta','MC',1990,40);
insert into jogador (id_time, id_pais, nome, posicao, nascimento, forca) values (10,1,'Gerson','MC',1990,42);
insert into jogador (id_time, id_pais, nome, posicao, nascimento, forca) values (10,1,'Bruno Henrique','AT',1990,42);
insert into jogador (id_time, id_pais, nome, posicao, nascimento, forca) values (10,1,'Gabriel Barbosa','AT',1990,40);
insert into jogador (id_time, id_pais, nome, posicao, nascimento, forca) values (10,1,'Pedro','AT',1990,40);
insert into jogador (id_time, id_pais, nome, posicao, nascimento, forca) values (10,1,'Michael','AT',1990,40);